In [1]:

class ClassName:
    #some functions and variables
    #function--used to perform the specific activity
    #variables--Data(memory)

SyntaxError: unexpected EOF while parsing (<ipython-input-1-67d4015738d9>, line 5)

In [2]:
def test():
    print('Test() for function')
    return
test()

Test() for function


In [3]:

class Demo:
    def test(self):
        print("test() for the class and method")
        return

obj=Demo()  #object creation
obj.test() #call for the method

test() for the class and method


In [4]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
p1.fact(5)#120

120

In [5]:

#Method
# def test(self,para1,para2)

In [6]:
class Demo2:
    def Accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        a=p1
        b=p2
        return
    def display(self):
        print("p1=",p1)
        print("p2=",p2)
c1=Demo2()
c1.accept(10,20)
c1.display()

AttributeError: 'Demo2' object has no attribute 'accept'

In [7]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [8]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [9]:

lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [10]:

lst=[1.0,2.4,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)

(2, 3)


In [12]:
#Re-shape the given array
#numpy.reshape(arrayName,reshape,order='C')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
#append some data--horizontally
#hstack(array1,array2)--will be automatically arranged in horizontal
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [14]:
#append some data--verlically
#vstack(array1,array2)--will be automatically arranged in vertical
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [15]:
#Generate random number from NP
a1=np.random.normal(5,0.5,10)
print(a1)

[4.39030414 5.31336017 4.81137475 4.88198417 4.72276445 6.02767234
 5.39264412 5.25080852 5.32494652 4.86856758]


In [16]:
#numpy.zeros() and numpy.one()
#Generate an array with all zeroes--numpy.zeros()
#numpy.zeroes(shape,dtype=float,order='C')

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros((2,2),dtype=np.int32)

array([[0, 0],
       [0, 0]])

In [18]:

#np.ones(shape,dtype=float,order='C')
np.ones((4,3),dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [21]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [22]:
#arange()--particular
#numpy.arrange(start,end,step)
#start-value
#end-value
#step-gap bet one value to another value
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [24]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [25]:
#Index and slicing of Numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [26]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Row:",a1[0])

First Row: [1 2 3]


In [27]:
a1=np.array([(1,2,3),(4,5,6)])
print("Second Row:",a1[1])

Second Row: [4 5 6]


In [28]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Column:",a1[:,1])

Slicing Column: [2 5]


In [29]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Last Column:",a1[:,2])

Slicing Last Column: [3 6]


In [30]:
a1=np.array([(1,2,3),(4,5,6)])
print("Row and Column",a1[1,:2])

Row and Column [4 5]


In [31]:
a1=np.array([(1,2,3),(4,5,6)])
print("Row and Column",a1[1,:1])

Row and Column [4]


In [32]:

a1=np.array([(1,2,3),(4,5,6)])
print("First row",a1[1][1])

First row 5


In [33]:
a1=np.random.normal(5,1,10)
print(a1)

[3.88083666 6.33227964 4.6944645  6.5247095  4.23516768 6.4633138
 5.41203878 6.10949209 4.86328611 3.89885804]


In [34]:

#Some math Operation on givrn random numbers
#Min--returns the least number
#Max--returns the Large number
#Mean--Mean
#Median--Median
#GD--Gaussian Distribution
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[3.59592994 3.97671537 5.47553368 4.37583914 4.60697684 4.90806701
 6.39548469 6.27123053 2.76080929 5.25560014]
Min value= 2.7608092882344937
Max value= 6.395484691087603
Mean value= 4.76221866137603
Median value= 4.757521924266994


In [35]:

#Multiply of 1D arrays
#numpy.dot(x,y)--
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [36]:

c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [37]:
b1=np.array([([1,5]),([6,9])])
b2=np.array([([1,3]),([1,6])])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [38]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"MobileNumber":[999,888,777,888,777,999],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"],}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd


In [39]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID  MobileNumber Address
01    Anil    anil@gmail.com           999     Hyd
02   Akhil   akhil@gmail.com           888     Hyd
03  Dinesh  dinesh@gmail.com           777     Hyd
04  Harsha  harsha@gmail.com           888     Hyd
05    Ajay    ajay@gmail.com           777     Hyd
06  Kranth  kranth@gmail.com           999     Hyd


In [40]:

#supermarket.csv-Analysis(which product having higher %of selling price)
#which product having least selling %

import pandas as pd
products=pd.read__csv('FileName.csv')
print(products)

AttributeError: module 'pandas' has no attribute 'read__csv'

In [41]:
import pandas as pd
product_sellingData=pd.read_csv('FileName.csv',index_col=1)
print(product_sellingData)

FileNotFoundError: [Errno 2] File b'FileName.csv' does not exist: b'FileName.csv'